services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_MAX_REQUEST_SIZE: 20000000

  app:
    build: .
    container_name: flight_weather_dev
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null  # Keeps it running for manual interaction
    depends_on:
      - kafka
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: flight_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql